### ISSUE TITLE
Rules with a Title (comment) do not show strike-through when disabled

### ISSUE THREAD

**Issue by SherylHohman** [johngodley/redirection#1358]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

Visual feedback that a rule is disabled when a Title property has been provided.

### Actual Behavior

When a Title (comment) has been supplied, a disabled rule looks exactly like an enabled rule in the list.

### Steps to reproduce

Add a redirection rule with Source url and Destination url.  Also add a Title.  Save.
Now disable that rule.  
In the redirects list, it looks exactly the same when disabled as when enabled.

The reason is that only the (source) url shows a strike-through (text) when the rule is disabled.  
But if a Title is supplied, the url is not visible in the list.

### Suggested fix

version 1) add strike-through to the title (when exists) and the rule is disabled.  
version 2) (my preference overall, but perhaps differs from author's vision):
                  always show (source) url. ie if title is present, show both source url AND title.
                  In this case, the url strike-though still provided user feedback on a disabled rule.
                  
### Environment

Please list your browser, browser version, version of WordPress and Redirection plugin.
WP 5.0.1, Redirection 3.6.3, Firefox 64.0

**Comment by SherylHohman** [comment]
I have a PR for both versions.  

But I cannot test.  I followed instructions but I get errors.   

- yarn install gives me errors:      
`yarn install v1.12.3
[1/5] Validating package.json...
warning redirection@3.7: The engine "wordpress" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > extract-text-webpack-plugin@3.0.2" has incorrect peer dependency "webpack@^3.1.0".
warning "request-promise > request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
warning " > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning " > request-promise@4.2.2" has unmet peer dependency "request@^2.34".
[5/5] Building fresh packages...
[1/2] ⡀ node-sass
error S:\Classes\Redirection_WP_plugin_SH_customizations\redirection\node_modules\shared-git-hooks: Command failed.
Exit code: 1
Command: node index.js
Arguments:
Directory: S:\Classes\Redirection_WP_plugin_SH_customizations\redirection\node_modules\shared-git-hooks
Output:
Symlinking shared-git-hooks runner in .git/hooks

fs.js:115
    throw err;
    ^

Error: EPERM: operation not permitted, symlink 'S:\Classes\Redirection_WP_plugin_SH_customizations\redirection\node_modules\shared-git-hooks\hook.sh' -> 'S:\Classes\Redirec
tion_WP_plugin_SH_customizations\redirection\.git\hooks\applypatch-msg'
    at Object.symlinkSync (fs.js:905:3)
    at Object.installHook (S:\Classes\Redirection_WP_plugin_SH_customizations\redirection\node_modules\shared-git-hooks\index.js:43:6)
    at hooks.forEach (S:\Classes\Redirection_WP_plugin_SH_customizations\redirection\node_modules\shared-git-hooks\index.js:73:39)
    at Array.forEach (<anonymous>)
    at installHooks (S:\Classes\Redirection_WP_plugin_SH_customizations\redirection\node_modules\shared-git-hooks\index.js:73:9)
    at Object.<anonymous> (S:\Classes\Redirection_WP_plugin_SH_customizations\redirection\node_modules\shared-git-hooks\index.js:89:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
`  

- Also, 'gulp pot' gives me errors:   
`sh (master) redirection $ gulp pot
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './.config.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (S:\Classes\Redirection_WP_plugin_SH_customizations\redirection\gulpfile.js:12:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)`

And `yarn run dist` gives me errors:  
`sh (master) redirection $ yarn run dist
yarn run v1.12.3
$ NODE_ENV=production webpack --progress --colors --config ./webpack.config.js --mode production
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`  

- Finally, I did not know how to do this:  
`To use in development mode then set REDIRECTION_DEV_MODE to true in PHP`   
Is there a file I must modify?  Is it something I type into the command line?  

I am sorry to bother you on this but I haven't found useful search terms to address these issues.  
I guess I am over my head on how to make a modified React for wordpress file/app ready for a use as WordPress plugin..  
I would *really* like to customize your plugin for my personal use, if nothing else.  
Can you be so kind as to point me in the right direction (tutorial ?) on how to set up my env, or whatever is needed to make this work??  

I have written a few React apps, though it's been a while.   I can hack wordpress php files, though I'm not fluent in either.   I've never worked with react for use inside wordpress.   

I am grateful for your plugin.  I am happy to contribute.   
Some UI customization are already listed as "Issues" some are not.   They may or may not fit into your vision, but I would be grateful if I can build on your work, even just for personal use.   

Can you help point me in the right direction so I can get a modified version of redirection compile(?) ready to upload into my wordpress plugin folder ??  

Thank You for your time.  

-Sheryl

PS. I am using Windows 10 (I know...) 
I installed the latest version of yarn, npm, gulp (as of 2 days ago)

**Comment by johngodley** [comment]
You will need to use a Linux/MacOS environment to build the plugin - it won't build on Windows

**Comment by johngodley** [comment]
Merged. Thanks!
