### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by DaveMuch** [johngodley/redirection#2035]
```
Plugin: 4.4.2
WordPress: 5.3-RC1-46566 (single)
PHP: 7.3.10
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3941.4 Safari/537.36
JavaScript: https://it-web-consulting.de/wp-content/plugins/redirection/redirection.js
REST API: https://it-web-consulting.de/wp-json/

Error: Unexpected token F in JSON at position 1 (SyntaxError)
Raw: 
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Jetpack_Custom_CSS_Enhancements::_wp_post_revision_fields(), 1 passed in /mnt/web207/b1/96/510053996/htdocs/WordPress-master/wp-includes/class-wp-hook.php on line 288 and exactly 2 expected in /mnt/web207/b1/96/510053996/htdocs/WordPress-master/wp-content/plugins/jetpack/modules/custom-css/custom-css-4.7.php:169
Stack trace:
#0 /mnt/web207/b1/96/510053996/htdocs/WordPress-master/wp-includes/class-wp-hook.php(288): Jetpack_Custom_CSS_Enhancements::_wp_post_revision_fields(Array)
#1 /mnt/web207/b1/96/510053996/htdocs/WordPress-master/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#2 /mnt/web207/b1/96/510053996/htdocs/WordPress-master/wp-content/plugins/wp-front-end-editor/class-wp-rest-post-autosave-controller.php(330): apply_filters('_wp_post_revisi...', Array)
#3 /mnt/web207/b1/96/510053996/htdocs/WordPress-master/wp-includes/rest-api/endpoints/class-wp-rest-controller.php(356): WP_REST_Post_Autosave_Controller->get_item_schema()
#4 in /mnt/web207/b1/96/510053996/htdocs/WordPress-master/wp-content/plugins/jetpack/modules/custom-css/custom-css-4.7.php on line 169

```

**Comment by johngodley** [comment]
Please see the message for cause:

`Uncaught ArgumentCountError: Too few arguments to function Jetpack_Custom_CSS_Enhancements::_wp_post_revision_fields()`

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
