### ISSUE TITLE
Permission plugin not working

### ISSUE THREAD

**Issue by wpmarmite** [johngodley/redirection#3000]
Hello,

I installed the sample permission plugin located at https://redirection.me/developer/permissions/
After activation, I get a fatal error. Here is what I get in the following in the debug log file : 

```
[27-Jul-2021 12:26:33 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function {closure}(), 1 passed in /Users/alexborto/Local Sites/wpmarmite/app/public/wp-includes/class-wp-hook.php on line 305 and exactly 2 expected in /Users/alexborto/Local Sites/wpmarmite/app/public/wp-content/plugins/advanced-redirection-permissions/advanced-redirection-permissions.php:13
Stack trace:
#0 /Users/alexborto/Local Sites/wpmarmite/app/public/wp-includes/class-wp-hook.php(305): {closure}('edit_posts')
#1 /Users/alexborto/Local Sites/wpmarmite/app/public/wp-includes/plugin.php(189): WP_Hook->apply_filters('edit_posts', Array)
#2 /Users/alexborto/Local Sites/wpmarmite/app/public/wp-content/plugins/redirection/redirection-capabilities.php(80): apply_filters('redirection_cap...', 'edit_posts', 'redirection_cap...')
#3 /Users/alexborto/Local Sites/wpmarmite/app/public/wp-content/plugins/redirection/redirection-admin.php(88): Redirection_Capabilities::has_access('redirection_cap...')
#4 /Users/alexborto/Local Sites/wpmarmite/app/public/wp-includes/cla in /Users/alexborto/Local Sites/wpmarmite/app/public/wp-content/plugins/advanced-redirection-permissions/advanced-redirection-permissions.php on line 13
```

Thanks for your help :)

Notes : 

I use WordPress 5.8 on a local installation, Redirection 5.1.3 and the permission plugin available [here](https://redirection.me/developer/permissions/).

**Comment by chesio** [comment]
Hi @wpmarmite,

the plugin file is missing important part at the end. The last line should be `}, 10, 2 );` instead of `} );`

If you replace the plugin contents with the example from [the very same page](https://redirection.me/developer/permissions/), it works fine:
```php
<?php

/*
Plugin Name: Advanced Redirection Permissions
Description: Advanced access to Redirection
Version: 0.2
*/

add_filter( 'redirection_role', function( $role ) {
  return 'edit_posts';  // Add your chosen capability or role here
} );

add_filter( 'redirection_capability_check', function( $capability, $permission_name ) {
     if ( $permission_name === 'redirection_cap_redirect_manage' || $permission_name === 'redirection_cap_redirect_add' ) {
         return $capability;
     }

     return 'manage_options';
}, 10, 2 );
```
