### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by GrynIlya** [johngodley/redirection#3012]
```
Plugin: 5.1.3 4.2
WordPress: 5.8 (single)
PHP: 7.4.3
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
JavaScript: https://nationalboilerspares.co.uk/wp-content/plugins/redirection/redirection.js?ver=5.1.3-81f455fc2a8faec560fb955b29f9a717
REST API: https://nationalboilerspares.co.uk/wp-json/
Query: ?page=redirection.php
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    at El (https://nationalboilerspares.co.uk/wp-content/plugins/redirection/redirection.js:2:440873)
    at p
    at div
    at _l (https://nationalboilerspares.co.uk/wp-content/plugins/redirection/redirection.js:2:440998)
    at qf (https://nationalboilerspares.co.uk/wp-content/plugins/redirection/redirection.js:2:533712)
    at div
    at a (https://nationalboilerspares.co.uk/wp-content/plugins/redirection/redirection.js:2:478596)
    at https://nationalboilerspares.co.uk/wp-content/plugins/redirection/redirection.js:2:723082
    at f (https://nationalboilerspares.co.uk/wp-content/plugins/redirection/redirection.js:2:372578)
    at Ue (https://nationalboilerspares.co.uk/wp-content/plugins/redirection/redirection.js:2:370533)
    at Tw
```

**Comment by johngodley** [comment]
What are you doing when this occurs?

**Comment by johngodley** [comment]
Closing for now, please reopen with more information.
