### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by DjThossi** [johngodley/redirection#670]
I just entered `/var/www/html/.redirects` in field `Apache Module` and got following error to see.

```
Plugin: 3.0.1
WordPress: 4.9.2
PHP: 7.2.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Error: Unexpected token < in JSON at position 0
Action: redirection/v1/setting POST
Params: {"support":false,"token":"bc488959008df87177e19f043ef82c28","monitor_post":0,"monitor_types":[],"associated_redirect":"","auto_target":"","expire_redirect":7,"expire_404":7,"modules":[],"newsletter":false,"redirect_cache":1,"ip_logging":1,"last_group_id":1,"location":"/var/www/html/.redirects"}
Code: 200 OK
Raw: <br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function get_plugin_data() in /var/www/html/wp-content/plugins/redirection/models/htaccess.php:162
Stack trace:
#0 /var/www/html/wp-content/plugins/redirection/models/htaccess.php(198): Red_Htaccess-&gt;generate()
#1 /var/www/html/wp-content/plugins/redirection/models/htaccess.php(220): Red_Htaccess-&gt;get('')
#2 /var/www/html/wp-content/plugins/redirection/modules/apache.php(49): Red_Htaccess-&gt;save('/var/www/html/....')
#3 /var/www/html/wp-content/plugins/redirection/modules/apache.php(67): Apache_Module-&gt;flush_module()
#4 /var/www/html/wp-content/plugins/redirection/redirection-settings.php(113): Apache_Module-&gt;update(Array)
#5 /var/www/html/wp-content/plugins/redirection/api/api-settings.php(22): red_set_options(Array)
#6 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(936): Redirection_Api_Settings-&gt;route_save_settings(Object(WP_REST_Request))
#7 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(321): WP_REST_Server-&gt;dispatch(Object(WP_REST_Request))
#8 / in <b>/var/www/html/wp-content/plugins/redirection/models/htaccess.php</b> on line <b>162</b><br />

```

**Comment by DjThossi** [comment]
For me, the error is gone with version 3.1
https://github.com/johngodley/redirection/releases/tag/3.1

**Comment by johngodley** [comment]
👍
